export const fallbackData = {
  generatedAt: '2026-06-19T10:54:13Z',
  source: 'Example data · run scripts/build_dashboard_data.py for current results',
  records: [
    { month: '2025-09', controlType: 'Extraction Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 28400, libraries: 12 },
    { month: '2025-09', controlType: 'Extraction Negative', kingdom: 'Plant', pipeline: 'EUKARYOTE', reads: 6200, libraries: 12 },
    { month: '2025-09', controlType: 'Library Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 17800, libraries: 9 },
    { month: '2025-09', controlType: 'Library Negative', kingdom: 'Animal', pipeline: 'EUKARYOTE', reads: 3200, libraries: 9 },
    { month: '2025-10', controlType: 'Extraction Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 35100, libraries: 14 },
    { month: '2025-10', controlType: 'Extraction Negative', kingdom: 'Other Eukaryote', pipeline: 'EUKARYOTE', reads: 7100, libraries: 14 },
    { month: '2025-10', controlType: 'Library Negative', kingdom: 'Plant', pipeline: 'EUKARYOTE', reads: 9800, libraries: 11 },
    { month: '2025-10', controlType: 'Library Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 23600, libraries: 11 },
    { month: '2025-11', controlType: 'Extraction Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 41200, libraries: 15 },
    { month: '2025-11', controlType: 'Extraction Negative', kingdom: 'Animal', pipeline: 'EUKARYOTE', reads: 12800, libraries: 15 },
    { month: '2025-11', controlType: 'Library Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 26500, libraries: 10 },
    { month: '2025-11', controlType: 'Library Negative', kingdom: 'Other Eukaryote', pipeline: 'EUKARYOTE', reads: 4400, libraries: 10 },
    { month: '2025-12', controlType: 'Extraction Negative', kingdom: 'Plant', pipeline: 'EUKARYOTE', reads: 18700, libraries: 13 },
    { month: '2025-12', controlType: 'Extraction Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 32200, libraries: 13 },
    { month: '2025-12', controlType: 'Library Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 19800, libraries: 8 },
    { month: '2025-12', controlType: 'Library Negative', kingdom: 'Animal', pipeline: 'EUKARYOTE', reads: 5600, libraries: 8 },
    { month: '2026-01', controlType: 'Extraction Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 58600, libraries: 17 },
    { month: '2026-01', controlType: 'Extraction Negative', kingdom: 'Other Eukaryote', pipeline: 'EUKARYOTE', reads: 14300, libraries: 17 },
    { month: '2026-01', controlType: 'Library Negative', kingdom: 'Plant', pipeline: 'EUKARYOTE', reads: 11900, libraries: 12 },
    { month: '2026-01', controlType: 'Library Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 34100, libraries: 12 },
    { month: '2026-02', controlType: 'Extraction Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 74300, libraries: 18 },
    { month: '2026-02', controlType: 'Extraction Negative', kingdom: 'Animal', pipeline: 'EUKARYOTE', reads: 21600, libraries: 18 },
    { month: '2026-02', controlType: 'Library Negative', kingdom: 'Bacteria', pipeline: 'PREFILTER', reads: 38200, libraries: 13 },
    { month: '2026-02', controlType: 'Library Negative', kingdom: 'Other Eukaryote', pipeline: 'EUKARYOTE', reads: 8300, libraries: 13 },
  ],
  taxa: [
    { name: 'Pseudomonas', kingdom: 'Bacteria', reads: 62400, change: 18.4 },
    { name: 'Ralstonia', kingdom: 'Bacteria', reads: 48150, change: 7.2 },
    { name: 'Homo', kingdom: 'Animal', reads: 33780, change: -4.6 },
    { name: 'Arabidopsis', kingdom: 'Plant', reads: 28440, change: 12.1 },
    { name: 'Malassezia', kingdom: 'Other Eukaryote', reads: 19620, change: 3.8 },
    { name: 'Bacillus', kingdom: 'Bacteria', reads: 16880, change: -8.3 },
    { name: 'Zea', kingdom: 'Plant', reads: 12430, change: 5.7 },
  ],
}
